"use server";

import { createServerClient } from "@/lib/supabase/server";
import { requireAuth } from "@/lib/actions/auth.actions";
import { isMatchingWeekday, resolveDateRange } from "@/lib/dashboard/filters";
import {
  aggregateCriticalProducts,
  aggregateGastoPorCategoria,
  aggregateMetrics,
  aggregateSpendingTrend,
  aggregateTopMerma,
  aggregateTopProductos,
  aggregateTopProveedores,
  buildProductLookup,
  buildSupplierLookup,
  type MermaRaw,
  type OrdenRaw,
  type ProductoRaw,
  type ProveedorRaw,
} from "@/lib/dashboard/aggregate";
import type { DashboardData, DashboardFilters, FilterMeta } from "@/types";

export async function getDashboardData(filters: DashboardFilters): Promise<DashboardData> {
  const auth = await requireAuth();
  if (auth.error) return emptyDashboardData(filters);
  const supabase = await createServerClient();
  const range = resolveDateRange(filters);

  // For 'dia' mode we cannot filter by weekday in SQL cleanly, so we fetch all
  // orders/mermas and JS-filter. For 'periodo'/'mes' the [prevStart, end) window
  // covers both current and prior periods in one query.
  const isDia = filters.mode === "dia";

  const productosQuery = supabase
    .from("productos")
    .select(
      "id, nombre, unidad, stock_actual, stock_minimo, last_price, categoria_id, categorias!inner(nombre)",
    );

  const proveedoresQuery = supabase.from("proveedores").select("id, company");

  // Use date-only strings for Supabase range filters so they are not sensitive
  // to the time component of the ISO bounds generated by resolveDateRange.
  const ordersQuery = isDia
    ? supabase
        .from("ordenes_compra")
        .select("id, supplier_id, fecha, total, detalle_orden(product_id, qty, price)")
    : supabase
        .from("ordenes_compra")
        .select("id, supplier_id, fecha, total, detalle_orden(product_id, qty, price)")
        .gte("fecha", range.prevStart.slice(0, 10))
        .lte("fecha", range.end.slice(0, 10));

  const mermasQuery = isDia
    ? supabase
        .from("movimientos")
        .select("id, product_id, fecha, qty, value_lost, motivo_merma")
        .eq("tipo", "merma")
    : supabase
        .from("movimientos")
        .select("id, product_id, fecha, qty, value_lost, motivo_merma")
        .eq("tipo", "merma")
        .gte("fecha", range.prevStart.slice(0, 10))
        .lte("fecha", range.end.slice(0, 10));

  const yearsQuery =
    filters.mode === "mes"
      ? supabase.from("ordenes_compra").select("fecha")
      : Promise.resolve({ data: null, error: null });

  const [productosRes, proveedoresRes, ordersRes, mermasRes, yearsRes] = await Promise.all([
    productosQuery,
    proveedoresQuery,
    ordersQuery,
    mermasQuery,
    yearsQuery,
  ]);

  // If tables don't exist yet, return empty data instead of crashing
  if (productosRes.error || proveedoresRes.error || ordersRes.error || mermasRes.error) {
    return emptyDashboardData(filters);
  }

  const productos = (productosRes.data ?? []) as unknown as ProductoRaw[];
  const proveedores = (proveedoresRes.data ?? []) as ProveedorRaw[];
  const allOrders = (ordersRes.data ?? []) as unknown as OrdenRaw[];
  const allMermas = (mermasRes.data ?? []) as MermaRaw[];

  // Compare only the date part (YYYY-MM-DD) to avoid timezone-offset issues.
  // end is inclusive so today's purchases are always included.
  const inRange = (iso: string, startIso: string, endIso: string) => {
    const d = iso.slice(0, 10);
    return d >= startIso.slice(0, 10) && d <= endIso.slice(0, 10);
  };

  let ordersCurrent: OrdenRaw[];
  let ordersPrior: OrdenRaw[];
  let mermasCurrent: MermaRaw[];
  let mermasPrior: MermaRaw[];

  if (isDia) {
    const { day } = filters;
    ordersCurrent = allOrders.filter((o) => isMatchingWeekday(o.fecha, day));
    ordersPrior = [];
    mermasCurrent = allMermas.filter((m) => isMatchingWeekday(m.fecha, day));
    mermasPrior = [];
  } else {
    ordersCurrent = allOrders.filter((o) => inRange(o.fecha, range.start, range.end));
    ordersPrior = allOrders.filter((o) => inRange(o.fecha, range.prevStart, range.prevEnd));
    mermasCurrent = allMermas.filter((m) => inRange(m.fecha, range.start, range.end));
    mermasPrior = allMermas.filter((m) => inRange(m.fecha, range.prevStart, range.prevEnd));
  }

  const productLookup = buildProductLookup(productos);
  const supplierLookup = buildSupplierLookup(proveedores);

  const metrics = aggregateMetrics({
    productos,
    ordersCurrent,
    ordersPrior,
    mermasCurrent,
    mermasPrior,
    includeChange: !isDia,
  });

  const spendingTrend = aggregateSpendingTrend({
    orders: ordersCurrent,
    mermas: mermasCurrent,
    startIso: range.start,
    bucketCount: range.bucketCount,
  });

  const availableYears = computeAvailableYears(
    (yearsRes.data as { fecha: string }[] | null) ?? null,
    allOrders,
  );

  const filterMeta: FilterMeta = {
    mode: filters.mode,
    period: filters.mode === "periodo" ? filters.period : undefined,
    month: filters.mode === "mes" ? filters.month : undefined,
    year: filters.mode === "mes" ? filters.year : undefined,
    day: filters.mode === "dia" ? filters.day : undefined,
    purchasesCount: ordersCurrent.length,
    availableYears,
  };

  return {
    metrics,
    topProductos: aggregateTopProductos(ordersCurrent, productLookup),
    topProveedores: aggregateTopProveedores(ordersCurrent, supplierLookup),
    topMerma: aggregateTopMerma(mermasCurrent, productLookup),
    criticalProducts: aggregateCriticalProducts(productos),
    spendingTrend,
    gastoPorCategoria: aggregateGastoPorCategoria(ordersCurrent, productLookup),
    filterMeta,
  };
}

function emptyDashboardData(filters: DashboardFilters): DashboardData {
  const now = new Date();
  const filterMeta: FilterMeta = {
    mode: filters.mode,
    period: filters.mode === "periodo" ? filters.period : undefined,
    month: filters.mode === "mes" ? filters.month : undefined,
    year: filters.mode === "mes" ? filters.year : undefined,
    day: filters.mode === "dia" ? filters.day : undefined,
    purchasesCount: 0,
    availableYears: [now.getFullYear()],
  };
  return {
    metrics: {
      totalInventario: { value: 0 },
      comprasDelMes: { value: 0 },
      mermaDelMes: { value: 0 },
      productosCriticos: 0,
    },
    topProductos: [],
    topProveedores: [],
    topMerma: [],
    criticalProducts: [],
    spendingTrend: [],
    gastoPorCategoria: {},
    filterMeta,
  };
}

function computeAvailableYears(
  yearsRows: { fecha: string }[] | null,
  fallbackOrders: OrdenRaw[],
): number[] {
  const set = new Set<number>();
  const source: { fecha: string }[] =
    yearsRows ?? fallbackOrders.map((o) => ({ fecha: o.fecha }));
  for (const r of source) {
    if (!r.fecha) continue;
    set.add(new Date(r.fecha).getFullYear());
  }
  if (set.size === 0) set.add(new Date().getFullYear());
  return [...set].sort((a, b) => b - a);
}
